# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    operator.knative.dev/mode: Reconcile
  labels:
    app: subresource-apiserver
    kf.dev/release: VERSION_PLACEHOLDER
  name: subresource-apiserver
  namespace: kf
spec:
  replicas: 3
  selector:
    matchLabels:
      app: subresource-apiserver
  template:
    metadata:
      labels:
        app: subresource-apiserver
        kf.dev/release: VERSION_PLACEHOLDER
      name: subresource-apiserver
    spec:
      serviceAccountName: controller
      containers:
      - name: subresource-apiserver
        image: ko://github.com/google/kf/v2/cmd/subresource-apiserver
        args: ["--secure-port=6443", "--cert-dir=/etc/kf/certs"]
        ports:
        - containerPort: 6443
          name: https
        - containerPort: 8080
          name: http
        volumeMounts:
        - mountPath: /tmp
          name: temp-vol
        - name: certs
          mountPath: "/etc/kf/certs"
          readOnly: false
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging
      volumes:
      - name: temp-vol
        emptyDir: {}
      - name: config-logging
        configMap:
          name: config-logging
      - name: certs
        secret:
          secretName: upload-api-server-secret
          items:
          - key: server-cert.pem
            path: apiserver.crt
          - key: server-key.pem
            path: apiserver.key
